# Generated by Django 4.2.5 on 2023-12-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0003_categoria_tarefa_delete_categorias_delete_tarefas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_cat',
            new_name='nome_categoria',
        ),
    ]
