# Generated by Django 4.2.5 on 2023-12-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_rename_nome_cat_categoria_nome_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='Tipo',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Movimentação', 'Movimentação'), ('Compra/Venda', 'Compra/Venda'), ('Desconhecido/Desaparecido', 'Desconhecido/Desaparecido'), ('Stand-by', 'Stand-by')], default='Stand-by', max_length=50),
        ),
    ]
